//! Intrusion Detection System (IDS) Engine.
//!
//! Ported from `sovereign_titan/security/ids_engine.py`.
//! Pattern-based and behavioral intrusion detection: port scan detection,
//! brute force, data exfiltration, lateral movement, connection rate spikes,
//! and DNS TXT base64 payload detection.

use std::collections::{HashMap, HashSet};
use std::net::IpAddr;
use std::time::{SystemTime, UNIX_EPOCH};

use regex::Regex;

/// Severity-to-score mapping.
const SEVERITY_SCORE_LOW: f32 = 0.35;
const SEVERITY_SCORE_MEDIUM: f32 = 0.55;
const SEVERITY_SCORE_HIGH: f32 = 0.75;
const SEVERITY_SCORE_CRITICAL: f32 = 0.90;

/// Auth-related ports (SSH, Telnet, RDP, SMB, VNC).
const AUTH_PORTS: &[u16] = &[22, 23, 3389, 445, 5900];

/// Common internal service ports (not suspicious for lateral movement).
const COMMON_INTERNAL_PORTS: &[u16] = &[22, 53, 80, 443, 445, 3389, 5985, 5986, 8080, 8443];

/// Ephemeral port range start — OS-assigned outbound ports.
const EPHEMERAL_PORT_MIN: u16 = 49152;

/// Alert cooldown in seconds (deduplication window).
const ALERT_COOLDOWN_SECS: f64 = 600.0;

/// Known-safe process names (lowercase, without .exe).
const SAFE_PROCESSES: &[&str] = &[
    "svchost", "system", "onedrive", "chrome", "firefox", "msedge",
    "explorer", "searchhost", "filecoauth", "claude", "code",
    "python", "node", "git", "docker", "wsl", "conhost",
    "runtimebroker", "sihost", "taskhostw", "ctfmon",
    "securityhealthservice", "mpcmdrun", "msmpeng",
    "smartscreen", "spoolsv", "lsass", "services",
    "windowsterminal", "powershell", "pwsh", "cmd",
];

/// A connection for the IDS to analyze.
#[derive(Debug, Clone)]
pub struct ConnectionInfo {
    pub local_addr: String,
    pub local_port: u16,
    pub remote_addr: String,
    pub remote_port: u16,
    pub process_name: String,
    pub status: String,
    pub direction: String,
    pub is_encrypted: bool,
}

/// An IDS detection rule.
#[derive(Debug, Clone)]
pub struct IDSRule {
    pub rule_id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub severity: &'static str,
    pub rule_type: &'static str,
    pub enabled: bool,
}

/// An alert generated by the IDS engine.
#[derive(Debug, Clone)]
pub struct IDSAlert {
    pub rule_id: String,
    pub rule_name: String,
    pub severity: String,
    pub source_ip: String,
    pub description: String,
    pub timestamp: f64,
}

/// Full IDS analysis report.
#[derive(Debug)]
pub struct IDSReport {
    pub timestamp: f64,
    pub connections_analyzed: usize,
    pub alerts: Vec<IDSAlert>,
    pub rules_checked: usize,
    pub rules_triggered: usize,
}

impl IDSReport {
    /// Generate a human-readable summary.
    pub fn summary(&self) -> String {
        let mut lines = vec![
            format!("IDS Report:"),
            format!("  Connections Analyzed: {}", self.connections_analyzed),
            format!("  Rules Checked: {}", self.rules_checked),
            format!("  Alerts: {}", self.alerts.len()),
        ];
        if self.alerts.is_empty() {
            lines.push("  No alerts — all clear".into());
        } else {
            for alert in self.alerts.iter().take(10) {
                lines.push(format!(
                    "    [{}] {}: {} (src: {})",
                    alert.severity.to_uppercase(),
                    alert.rule_id,
                    alert.description,
                    alert.source_ip,
                ));
            }
        }
        lines.join("\n")
    }
}

/// Get the severity score for alert classification.
pub fn severity_score(severity: &str) -> f32 {
    match severity {
        "low" => SEVERITY_SCORE_LOW,
        "medium" => SEVERITY_SCORE_MEDIUM,
        "high" => SEVERITY_SCORE_HIGH,
        "critical" => SEVERITY_SCORE_CRITICAL,
        _ => SEVERITY_SCORE_MEDIUM,
    }
}

/// Pattern-based and behavioral intrusion detection engine.
pub struct IDSEngine {
    rules: Vec<IDSRule>,
    alerts: Vec<IDSAlert>,
    max_alerts: usize,
    reported_alerts: HashMap<String, f64>,
    // Behavioral tracking state.
    port_scan_tracker: HashMap<String, (HashSet<u16>, f64)>,
    brute_force_tracker: HashMap<String, (Vec<f64>, f64)>,
    rate_tracker: HashMap<String, Vec<f64>>,
}

impl IDSEngine {
    /// Create a new engine with default rules.
    pub fn new() -> Self {
        Self {
            rules: default_rules(),
            alerts: Vec::new(),
            max_alerts: 1000,
            reported_alerts: HashMap::new(),
            port_scan_tracker: HashMap::new(),
            brute_force_tracker: HashMap::new(),
            rate_tracker: HashMap::new(),
        }
    }

    /// Run all enabled rules against connection data.
    pub fn analyze(
        &mut self,
        connections: &[ConnectionInfo],
        dns_records: Option<&[DnsRecordRef<'_>]>,
    ) -> IDSReport {
        let now = now_secs();
        let mut alerts = Vec::new();
        let mut rules_checked = 0;
        let mut rules_triggered = HashSet::new();

        // Collect enabled rule metadata to avoid borrowing self.rules
        // while calling self.eval_* methods that mutate tracker state.
        let enabled_rules: Vec<(&'static str, &'static str, &'static str)> = self
            .rules
            .iter()
            .filter(|r| r.enabled)
            .map(|r| (r.rule_id, r.name, r.severity))
            .collect();

        for &(rule_id, rule_name, severity) in &enabled_rules {
            rules_checked += 1;

            let rule_ref = IDSRule {
                rule_id,
                name: rule_name,
                description: "",
                severity,
                rule_type: "",
                enabled: true,
            };

            let new_alerts = match rule_id {
                "BEH-001" => self.eval_port_scan(connections, &rule_ref, now),
                "BEH-002" => self.eval_brute_force(connections, &rule_ref, now),
                "BEH-003" => self.eval_exfiltration(connections, &rule_ref),
                "RATE-001" => self.eval_rate_spike(connections, &rule_ref, now),
                "LAT-001" => self.eval_lateral_movement(connections, &rule_ref),
                "SIG-001" => self.eval_dns_txt_payload(dns_records, &rule_ref),
                _ => Vec::new(),
            };

            if !new_alerts.is_empty() {
                rules_triggered.insert(rule_id);
                alerts.extend(new_alerts);
            }
        }

        // Deduplicate alerts within cooldown window.
        let deduped: Vec<IDSAlert> = alerts
            .into_iter()
            .filter(|alert| {
                let key = format!("{}|{}", alert.rule_id, alert.source_ip);
                if let Some(&last) = self.reported_alerts.get(&key) {
                    if now - last < ALERT_COOLDOWN_SECS {
                        return false;
                    }
                }
                self.reported_alerts.insert(key, now);
                true
            })
            .collect();

        // Store alerts (capped).
        self.alerts.extend(deduped.clone());
        if self.alerts.len() > self.max_alerts {
            let excess = self.alerts.len() - self.max_alerts;
            self.alerts.drain(..excess);
        }

        IDSReport {
            timestamp: now,
            connections_analyzed: connections.len(),
            alerts: deduped,
            rules_checked,
            rules_triggered: rules_triggered.len(),
        }
    }

    /// Get recent alerts, optionally filtered by severity.
    pub fn get_alerts(&self, severity: Option<&str>, limit: usize) -> Vec<&IDSAlert> {
        let filtered: Vec<&IDSAlert> = self
            .alerts
            .iter()
            .filter(|a| severity.is_none_or(|s| a.severity == s))
            .collect();
        let start = filtered.len().saturating_sub(limit);
        filtered[start..].to_vec()
    }

    /// Get all registered rules.
    pub fn get_rules(&self) -> &[IDSRule] {
        &self.rules
    }

    /// Enable a rule by ID.
    pub fn enable_rule(&mut self, rule_id: &str) -> bool {
        if let Some(rule) = self.rules.iter_mut().find(|r| r.rule_id == rule_id) {
            rule.enabled = true;
            return true;
        }
        false
    }

    /// Disable a rule by ID.
    pub fn disable_rule(&mut self, rule_id: &str) -> bool {
        if let Some(rule) = self.rules.iter_mut().find(|r| r.rule_id == rule_id) {
            rule.enabled = false;
            return true;
        }
        false
    }

    // ── Rule Evaluators ──────────────────────────────────────────────────

    /// BEH-001: Port scan detection (>20 unique non-ephemeral ports/60s).
    fn eval_port_scan(
        &mut self,
        connections: &[ConnectionInfo],
        rule: &IDSRule,
        now: f64,
    ) -> Vec<IDSAlert> {
        let mut alerts = Vec::new();
        let mut ip_ports: HashMap<&str, HashSet<u16>> = HashMap::new();

        for conn in connections {
            if conn.remote_addr.is_empty() || conn.status == "LISTEN" {
                continue;
            }
            if is_loopback(&conn.remote_addr) || is_safe_process(&conn.process_name) {
                continue;
            }
            if conn.local_port >= EPHEMERAL_PORT_MIN {
                continue;
            }
            ip_ports
                .entry(&conn.remote_addr)
                .or_default()
                .insert(conn.local_port);
        }

        for (ip, ports) in &ip_ports {
            let tracker = self
                .port_scan_tracker
                .entry(ip.to_string())
                .or_insert_with(|| (HashSet::new(), now));

            if now - tracker.1 > 60.0 {
                tracker.0.clear();
                tracker.1 = now;
            }
            tracker.0.extend(ports);

            if tracker.0.len() > 20 {
                alerts.push(IDSAlert {
                    rule_id: rule.rule_id.to_string(),
                    rule_name: rule.name.to_string(),
                    severity: rule.severity.to_string(),
                    source_ip: ip.to_string(),
                    description: format!("Port scan: {} unique ports from {ip}", tracker.0.len()),
                    timestamp: now,
                });
                tracker.0.clear();
                tracker.1 = 0.0;
            }
        }
        alerts
    }

    /// BEH-002: Brute force detection (>10 auth port attempts/120s).
    fn eval_brute_force(
        &mut self,
        connections: &[ConnectionInfo],
        rule: &IDSRule,
        now: f64,
    ) -> Vec<IDSAlert> {
        let mut alerts = Vec::new();
        let auth_ports: HashSet<u16> = AUTH_PORTS.iter().copied().collect();
        let mut ip_auth: HashMap<&str, usize> = HashMap::new();

        for conn in connections {
            if conn.remote_addr.is_empty()
                || is_loopback(&conn.remote_addr)
                || is_safe_process(&conn.process_name)
            {
                continue;
            }
            if auth_ports.contains(&conn.local_port) {
                *ip_auth.entry(&conn.remote_addr).or_insert(0) += 1;
            }
        }

        for (ip, count) in &ip_auth {
            let tracker = self
                .brute_force_tracker
                .entry(ip.to_string())
                .or_insert_with(|| (Vec::new(), now));

            if now - tracker.1 > 120.0 {
                tracker.0.clear();
                tracker.1 = now;
            }

            for _ in 0..*count {
                tracker.0.push(now);
            }
            tracker.0.retain(|&t| now - t < 120.0);

            if tracker.0.len() > 10 {
                alerts.push(IDSAlert {
                    rule_id: rule.rule_id.to_string(),
                    rule_name: rule.name.to_string(),
                    severity: rule.severity.to_string(),
                    source_ip: ip.to_string(),
                    description: format!(
                        "Brute force: {} auth attempts from {ip}",
                        tracker.0.len()
                    ),
                    timestamp: now,
                });
                tracker.0.clear();
                tracker.1 = 0.0;
            }
        }
        alerts
    }

    /// BEH-003: Data exfiltration (>50 outbound connections from single non-safe process).
    fn eval_exfiltration(
        &self,
        connections: &[ConnectionInfo],
        rule: &IDSRule,
    ) -> Vec<IDSAlert> {
        let mut alerts = Vec::new();
        let mut process_outbound: HashMap<&str, usize> = HashMap::new();

        for conn in connections {
            if conn.direction == "outbound"
                && !conn.process_name.is_empty()
                && !is_safe_process(&conn.process_name)
            {
                *process_outbound.entry(&conn.process_name).or_insert(0) += 1;
            }
        }

        for (proc, count) in &process_outbound {
            if *count > 50 {
                alerts.push(IDSAlert {
                    rule_id: rule.rule_id.to_string(),
                    rule_name: rule.name.to_string(),
                    severity: rule.severity.to_string(),
                    source_ip: "localhost".to_string(),
                    description: format!(
                        "Possible data exfiltration: {proc} has {count} outbound connections"
                    ),
                    timestamp: now_secs(),
                });
            }
        }
        alerts
    }

    /// RATE-001: Connection rate spike (>50 connections/60s from single IP).
    fn eval_rate_spike(
        &mut self,
        connections: &[ConnectionInfo],
        rule: &IDSRule,
        now: f64,
    ) -> Vec<IDSAlert> {
        let mut alerts = Vec::new();
        let mut ip_counts: HashMap<&str, usize> = HashMap::new();
        let mut ip_has_unsafe: HashMap<&str, bool> = HashMap::new();

        for conn in connections {
            if conn.remote_addr.is_empty() || is_loopback(&conn.remote_addr) {
                continue;
            }
            *ip_counts.entry(&conn.remote_addr).or_insert(0) += 1;
            if !is_safe_process(&conn.process_name) {
                ip_has_unsafe.insert(&conn.remote_addr, true);
            }
        }

        for (ip, count) in &ip_counts {
            if !ip_has_unsafe.get(ip).copied().unwrap_or(false) {
                continue;
            }

            let tracker = self.rate_tracker.entry(ip.to_string()).or_default();
            for _ in 0..*count {
                tracker.push(now);
            }
            tracker.retain(|&t| now - t < 60.0);

            if tracker.len() > 50 {
                alerts.push(IDSAlert {
                    rule_id: rule.rule_id.to_string(),
                    rule_name: rule.name.to_string(),
                    severity: rule.severity.to_string(),
                    source_ip: ip.to_string(),
                    description: format!(
                        "Connection spike: {} from {ip} in 60s",
                        tracker.len()
                    ),
                    timestamp: now,
                });
            }
        }
        alerts
    }

    /// LAT-001: Lateral movement (internal→internal on unusual ports).
    fn eval_lateral_movement(
        &self,
        connections: &[ConnectionInfo],
        rule: &IDSRule,
    ) -> Vec<IDSAlert> {
        let mut alerts = Vec::new();
        let common_ports: HashSet<u16> = COMMON_INTERNAL_PORTS.iter().copied().collect();

        for conn in connections {
            if conn.status == "LISTEN" || conn.remote_addr.is_empty() {
                continue;
            }
            if is_loopback(&conn.remote_addr) || is_loopback(&conn.local_addr) {
                continue;
            }
            if is_safe_process(&conn.process_name) {
                continue;
            }
            if conn.remote_port >= EPHEMERAL_PORT_MIN || conn.remote_port == 0 {
                continue;
            }
            if is_private_ip(&conn.remote_addr) && is_private_ip(&conn.local_addr) {
                if !common_ports.contains(&conn.remote_port) {
                    alerts.push(IDSAlert {
                        rule_id: rule.rule_id.to_string(),
                        rule_name: rule.name.to_string(),
                        severity: rule.severity.to_string(),
                        source_ip: conn.remote_addr.clone(),
                        description: format!(
                            "Lateral movement: {} → {}:{} ({})",
                            conn.local_addr,
                            conn.remote_addr,
                            conn.remote_port,
                            if conn.process_name.is_empty() {
                                "unknown"
                            } else {
                                &conn.process_name
                            },
                        ),
                        timestamp: now_secs(),
                    });
                }
            }
        }
        alerts
    }

    /// SIG-001: DNS TXT base64 payload detection.
    fn eval_dns_txt_payload(
        &self,
        dns_records: Option<&[DnsRecordRef<'_>]>,
        rule: &IDSRule,
    ) -> Vec<IDSAlert> {
        let records = match dns_records {
            Some(r) => r,
            None => return Vec::new(),
        };

        let base64_re = Regex::new(r"^[A-Za-z0-9+/]{50,}={0,2}$").unwrap();
        let mut alerts = Vec::new();

        for record in records {
            let domain = record.domain.to_lowercase();
            // Skip known-good parent domains.
            if has_known_good_parent(&domain) {
                continue;
            }

            for part in domain.split('.') {
                if base64_re.is_match(part) {
                    alerts.push(IDSAlert {
                        rule_id: rule.rule_id.to_string(),
                        rule_name: rule.name.to_string(),
                        severity: rule.severity.to_string(),
                        source_ip: "dns".to_string(),
                        description: format!("Base64 payload in DNS label: {domain}"),
                        timestamp: now_secs(),
                    });
                    break;
                }
            }
        }
        alerts
    }
}

impl Default for IDSEngine {
    fn default() -> Self {
        Self::new()
    }
}

/// Lightweight DNS record reference for IDS analysis.
#[derive(Debug)]
pub struct DnsRecordRef<'a> {
    pub domain: &'a str,
    pub record_type: &'a str,
    pub data: &'a str,
}

/// Build the default set of 6 IDS rules.
fn default_rules() -> Vec<IDSRule> {
    vec![
        IDSRule {
            rule_id: "BEH-001",
            name: "Port Scan Detection",
            description: "Detects >20 unique ports accessed by single source in 60s",
            severity: "high",
            rule_type: "behavioral",
            enabled: true,
        },
        IDSRule {
            rule_id: "BEH-002",
            name: "Brute Force Detection",
            description: "Detects >10 auth port attempts in 120s",
            severity: "high",
            rule_type: "behavioral",
            enabled: true,
        },
        IDSRule {
            rule_id: "BEH-003",
            name: "Data Exfiltration Detection",
            description: "Detects >50 outbound connections from single unknown process",
            severity: "critical",
            rule_type: "behavioral",
            enabled: true,
        },
        IDSRule {
            rule_id: "RATE-001",
            name: "Connection Rate Spike",
            description: "Detects >50 connections from single IP in 60s",
            severity: "medium",
            rule_type: "rate",
            enabled: true,
        },
        IDSRule {
            rule_id: "LAT-001",
            name: "Lateral Movement Detection",
            description: "Detects internal-to-internal connections on unusual ports",
            severity: "high",
            rule_type: "lateral",
            enabled: true,
        },
        IDSRule {
            rule_id: "SIG-001",
            name: "DNS TXT Base64 Payload",
            description: "Detects base64-encoded payloads in DNS labels",
            severity: "medium",
            rule_type: "signature",
            enabled: true,
        },
    ]
}

// ── Helpers ──────────────────────────────────────────────────────────────

/// Get current time as seconds since UNIX epoch.
fn now_secs() -> f64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs_f64()
}

/// Check if a process name is in the safe list.
pub fn is_safe_process(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let stem = name
        .to_lowercase()
        .trim_end_matches(".exe")
        .trim_end_matches(".com")
        .to_string();
    SAFE_PROCESSES.contains(&stem.as_str())
}

/// Check if an IP address is loopback.
pub fn is_loopback(ip: &str) -> bool {
    matches!(ip, "127.0.0.1" | "::1" | "0.0.0.0" | "::")
        || ip
            .parse::<IpAddr>()
            .map(|a| a.is_loopback())
            .unwrap_or(false)
}

/// Check if an IP address is private/internal.
pub fn is_private_ip(ip: &str) -> bool {
    match ip.parse::<IpAddr>() {
        Ok(IpAddr::V4(v4)) => v4.is_private() || v4.is_loopback() || v4.is_link_local(),
        Ok(IpAddr::V6(v6)) => v6.is_loopback(),
        Err(_) => false,
    }
}

/// Check if a domain has a known-good parent (skip heuristics).
pub fn has_known_good_parent(domain: &str) -> bool {
    const KNOWN_GOOD: &[&str] = &[
        "a2z.com", "amazonaws.com", "amazon.com", "windows.com",
        "microsoft.com", "microsoftonline.com", "apple.com",
        "icloud.com", "google.com", "googleapis.com", "gstatic.com",
        "cloudfront.net", "akamaiedge.net", "akadns.net",
        "azureedge.net", "trafficmanager.net", "office.com",
        "office365.com", "live.com", "outlook.com",
        "xboxlive.com", "xbox.com", "skype.com", "msn.com",
        "bing.com", "windowsupdate.com", "digicert.com",
    ];
    let domain = domain.trim_end_matches('.');
    for parent in KNOWN_GOOD {
        if domain == *parent || domain.ends_with(&format!(".{parent}")) {
            return true;
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_conn(
        remote_addr: &str,
        local_port: u16,
        remote_port: u16,
        process: &str,
        status: &str,
    ) -> ConnectionInfo {
        ConnectionInfo {
            local_addr: "192.168.1.100".into(),
            local_port,
            remote_addr: remote_addr.into(),
            remote_port,
            process_name: process.into(),
            status: status.into(),
            direction: "outbound".into(),
            is_encrypted: false,
        }
    }

    #[test]
    fn test_default_rules() {
        let engine = IDSEngine::new();
        assert_eq!(engine.get_rules().len(), 6);
        assert!(engine.get_rules().iter().all(|r| r.enabled));
    }

    #[test]
    fn test_safe_process() {
        assert!(is_safe_process("chrome.exe"));
        assert!(is_safe_process("Chrome"));
        assert!(is_safe_process("svchost"));
        assert!(!is_safe_process("malware"));
        assert!(!is_safe_process(""));
    }

    #[test]
    fn test_is_loopback() {
        assert!(is_loopback("127.0.0.1"));
        assert!(is_loopback("::1"));
        assert!(is_loopback("0.0.0.0"));
        assert!(!is_loopback("192.168.1.1"));
        assert!(!is_loopback("8.8.8.8"));
    }

    #[test]
    fn test_is_private_ip() {
        assert!(is_private_ip("192.168.1.1"));
        assert!(is_private_ip("10.0.0.1"));
        assert!(is_private_ip("172.16.0.1"));
        assert!(!is_private_ip("8.8.8.8"));
    }

    #[test]
    fn test_known_good_parent() {
        assert!(has_known_good_parent("foo.google.com"));
        assert!(has_known_good_parent("google.com"));
        assert!(has_known_good_parent("sub.microsoft.com"));
        assert!(!has_known_good_parent("evil-domain.tk"));
    }

    #[test]
    fn test_no_alerts_clean_traffic() {
        let mut engine = IDSEngine::new();
        let connections = vec![
            make_conn("8.8.8.8", 443, 53, "chrome.exe", "ESTABLISHED"),
            make_conn("127.0.0.1", 3000, 3000, "node", "ESTABLISHED"),
        ];
        let report = engine.analyze(&connections, None);
        assert!(report.alerts.is_empty());
    }

    #[test]
    fn test_exfiltration_detection() {
        let mut engine = IDSEngine::new();
        // 60 outbound connections from unknown process.
        let connections: Vec<ConnectionInfo> = (0..60)
            .map(|i| ConnectionInfo {
                local_addr: "192.168.1.100".into(),
                local_port: 50000 + i,
                remote_addr: format!("10.0.0.{}", i % 255),
                remote_port: 443,
                process_name: "suspiciousapp".into(),
                status: "ESTABLISHED".into(),
                direction: "outbound".into(),
                is_encrypted: false,
            })
            .collect();
        let report = engine.analyze(&connections, None);
        assert!(
            report.alerts.iter().any(|a| a.rule_id == "BEH-003"),
            "Should detect data exfiltration"
        );
    }

    #[test]
    fn test_enable_disable_rule() {
        let mut engine = IDSEngine::new();
        assert!(engine.disable_rule("BEH-001"));
        assert!(!engine.get_rules().iter().find(|r| r.rule_id == "BEH-001").unwrap().enabled);
        assert!(engine.enable_rule("BEH-001"));
        assert!(engine.get_rules().iter().find(|r| r.rule_id == "BEH-001").unwrap().enabled);
        assert!(!engine.enable_rule("NONEXISTENT"));
    }

    #[test]
    fn test_severity_score() {
        assert_eq!(severity_score("low"), SEVERITY_SCORE_LOW);
        assert_eq!(severity_score("critical"), SEVERITY_SCORE_CRITICAL);
        assert_eq!(severity_score("unknown"), SEVERITY_SCORE_MEDIUM);
    }

    #[test]
    fn test_dns_base64_detection() {
        let engine = IDSEngine::new();
        let rule = &engine.rules[5]; // SIG-001
        let long_b64 = "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB";
        let domain = format!("{long_b64}.evil.tk");
        let records = vec![DnsRecordRef {
            domain: &domain,
            record_type: "TXT",
            data: "",
        }];
        let alerts = engine.eval_dns_txt_payload(Some(&records), rule);
        assert!(!alerts.is_empty(), "Should detect base64 DNS payload");
    }

    #[test]
    fn test_alert_dedup() {
        let mut engine = IDSEngine::new();
        // Generate two identical exfiltration scenarios in quick succession.
        let connections: Vec<ConnectionInfo> = (0..60)
            .map(|i| ConnectionInfo {
                local_addr: "192.168.1.100".into(),
                local_port: 50000 + i,
                remote_addr: "10.0.0.1".into(),
                remote_port: 443,
                process_name: "badapp".into(),
                status: "ESTABLISHED".into(),
                direction: "outbound".into(),
                is_encrypted: false,
            })
            .collect();
        let report1 = engine.analyze(&connections, None);
        let report2 = engine.analyze(&connections, None);
        // Second report should have the same alert deduped.
        let beh003_1 = report1.alerts.iter().filter(|a| a.rule_id == "BEH-003").count();
        let beh003_2 = report2.alerts.iter().filter(|a| a.rule_id == "BEH-003").count();
        assert!(beh003_1 > 0);
        assert_eq!(beh003_2, 0, "Duplicate alert should be suppressed by cooldown");
    }
}
