//! Unified voice interface — combines STT and TTS with phase tracking.
//!
//! Provides a state-machine-based voice interface that manages the full
//! voice interaction lifecycle: idle, scanning for wake words, listening,
//! recording, processing (transcription), and speaking (synthesis).

use std::collections::VecDeque;
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use super::stt::{SpeechToText, SttConfig};
use super::tts::{TextToSpeech, TtsConfig};

/// Voice interface state machine phase.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum VoicePhase {
    /// Not actively listening.
    Idle,
    /// Scanning audio stream for wake word.
    Scanning,
    /// Wake word detected, preparing to record.
    Listening,
    /// Actively recording audio input.
    Recording,
    /// Processing recorded audio (transcription).
    Processing,
    /// Playing back synthesized speech.
    Speaking,
}

impl std::fmt::Display for VoicePhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            VoicePhase::Idle => write!(f, "idle"),
            VoicePhase::Scanning => write!(f, "scanning"),
            VoicePhase::Listening => write!(f, "listening"),
            VoicePhase::Recording => write!(f, "recording"),
            VoicePhase::Processing => write!(f, "processing"),
            VoicePhase::Speaking => write!(f, "speaking"),
        }
    }
}

/// An event generated by the voice interface.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VoiceEvent {
    /// Event type identifier (e.g. "transcription", "phase_change", "error").
    pub event_type: String,
    /// Associated text content (transcription result, spoken text, etc.).
    pub text: Option<String>,
    /// When the event occurred (seconds since UNIX epoch).
    pub timestamp: f64,
}

/// Configuration for the unified voice interface.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VoiceConfig {
    /// Optional wake word to trigger listening (e.g. "hey titan").
    pub wake_word: Option<String>,
    /// Maximum listen duration in seconds before auto-stop.
    pub listen_duration: f64,
    /// Minimum audio energy threshold for voice activity detection.
    pub energy_threshold: f64,
    /// Whether to automatically synthesize and speak responses.
    pub auto_respond: bool,
}

impl Default for VoiceConfig {
    fn default() -> Self {
        Self {
            wake_word: None,
            listen_duration: 5.0,
            energy_threshold: 300.0,
            auto_respond: false,
        }
    }
}

/// Status snapshot of the voice interface.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VoiceStatus {
    /// Current phase of the voice state machine.
    pub phase: VoicePhase,
    /// Whether the interface is actively listening.
    pub listening: bool,
    /// Whether auto-respond is enabled.
    pub auto_respond: bool,
    /// Whether STT is available.
    pub stt_available: bool,
    /// Whether TTS is available.
    pub tts_available: bool,
    /// Number of pending events.
    pub pending_events: usize,
}

/// Unified voice interface combining STT and TTS with state management.
///
/// Manages the voice interaction lifecycle through a state machine,
/// producing events that the caller can consume. Delegates actual
/// audio processing to the STT and TTS subsystems.
pub struct VoiceInterface {
    /// Interface configuration.
    config: VoiceConfig,
    /// Speech-to-text engine.
    stt: SpeechToText,
    /// Text-to-speech engine.
    tts: TextToSpeech,
    /// Current state machine phase.
    phase: VoicePhase,
    /// Whether the interface is actively listening.
    listening: bool,
    /// Event queue for consumers.
    events: VecDeque<VoiceEvent>,
}

impl VoiceInterface {
    /// Create a new voice interface with the given configuration.
    pub fn new(config: VoiceConfig) -> Self {
        let stt_config = SttConfig {
            energy_threshold: config.energy_threshold,
            ..SttConfig::default()
        };
        let tts_config = TtsConfig::default();

        Self {
            config,
            stt: SpeechToText::new(stt_config),
            tts: TextToSpeech::new(tts_config),
            phase: VoicePhase::Idle,
            listening: false,
            events: VecDeque::new(),
        }
    }

    /// Start listening for voice input.
    ///
    /// Transitions to Scanning if a wake word is configured, otherwise
    /// transitions directly to Listening.
    pub fn start_listening(&mut self) {
        if self.listening {
            return;
        }

        self.listening = true;

        if self.config.wake_word.is_some() {
            self.set_phase(VoicePhase::Scanning);
        } else {
            self.set_phase(VoicePhase::Listening);
        }

        self.push_event("listening_started", None);
    }

    /// Stop listening for voice input and return to Idle.
    pub fn stop_listening(&mut self) {
        if !self.listening {
            return;
        }

        self.listening = false;
        self.set_phase(VoicePhase::Idle);
        self.push_event("listening_stopped", None);
    }

    /// Toggle listening state. Returns the new listening state.
    pub fn toggle_listening(&mut self) -> bool {
        if self.listening {
            self.stop_listening();
        } else {
            self.start_listening();
        }
        self.listening
    }

    /// Enable or disable auto-respond mode.
    pub fn set_auto_respond(&mut self, enabled: bool) {
        self.config.auto_respond = enabled;
        self.push_event(
            "auto_respond_changed",
            Some(if enabled { "enabled" } else { "disabled" }),
        );
    }

    /// Drain all pending events from the queue.
    pub fn drain_events(&mut self) -> Vec<VoiceEvent> {
        self.events.drain(..).collect()
    }

    /// Get the current voice interface status.
    pub fn get_status(&self) -> VoiceStatus {
        VoiceStatus {
            phase: self.phase.clone(),
            listening: self.listening,
            auto_respond: self.config.auto_respond,
            stt_available: self.stt.is_available(),
            tts_available: self.tts.is_available(),
            pending_events: self.events.len(),
        }
    }

    /// Get a reference to the current phase.
    pub fn phase(&self) -> &VoicePhase {
        &self.phase
    }

    /// Check if the interface is currently listening.
    pub fn is_listening(&self) -> bool {
        self.listening
    }

    /// Get a reference to the voice configuration.
    pub fn config(&self) -> &VoiceConfig {
        &self.config
    }

    /// Get a mutable reference to the STT engine.
    pub fn stt_mut(&mut self) -> &mut SpeechToText {
        &mut self.stt
    }

    /// Get a mutable reference to the TTS engine.
    pub fn tts_mut(&mut self) -> &mut TextToSpeech {
        &mut self.tts
    }

    /// Speak the given text through TTS (convenience method).
    ///
    /// Transitions to Speaking phase, invokes TTS, then returns to
    /// the previous phase.
    pub fn speak(&mut self, text: &str) -> Result<(), String> {
        let prev_phase = self.phase.clone();
        self.set_phase(VoicePhase::Speaking);

        let result = self.tts.speak(text);

        // Restore previous phase regardless of result.
        self.set_phase(prev_phase);

        match result {
            Ok(_) => {
                self.push_event("spoke", Some(text));
                Ok(())
            }
            Err(e) => {
                self.push_event("speak_error", Some(&e));
                Err(e)
            }
        }
    }

    // ── Internal helpers ────────────────────────────────────────────────

    /// Transition to a new phase and emit a phase_change event.
    fn set_phase(&mut self, new_phase: VoicePhase) {
        if self.phase != new_phase {
            let old = self.phase.clone();
            self.phase = new_phase.clone();
            self.push_event(
                "phase_change",
                Some(&format!("{old} -> {new_phase}")),
            );
        }
    }

    /// Push an event onto the queue.
    fn push_event(&mut self, event_type: &str, text: Option<&str>) {
        self.events.push_back(VoiceEvent {
            event_type: event_type.to_string(),
            text: text.map(|s| s.to_string()),
            timestamp: now_secs(),
        });
    }
}

/// Get current time as seconds since UNIX epoch.
fn now_secs() -> f64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs_f64()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = VoiceConfig::default();
        assert!(config.wake_word.is_none());
        assert!((config.listen_duration - 5.0).abs() < f64::EPSILON);
        assert!((config.energy_threshold - 300.0).abs() < f64::EPSILON);
        assert!(!config.auto_respond);
    }

    #[test]
    fn test_initial_state() {
        let vi = VoiceInterface::new(VoiceConfig::default());
        assert_eq!(*vi.phase(), VoicePhase::Idle);
        assert!(!vi.is_listening());

        let status = vi.get_status();
        assert_eq!(status.phase, VoicePhase::Idle);
        assert!(!status.listening);
        assert!(!status.auto_respond);
    }

    #[test]
    fn test_start_stop_listening() {
        let mut vi = VoiceInterface::new(VoiceConfig::default());

        vi.start_listening();
        assert!(vi.is_listening());
        assert_eq!(*vi.phase(), VoicePhase::Listening);

        vi.stop_listening();
        assert!(!vi.is_listening());
        assert_eq!(*vi.phase(), VoicePhase::Idle);
    }

    #[test]
    fn test_start_with_wake_word() {
        let config = VoiceConfig {
            wake_word: Some("hey titan".to_string()),
            ..VoiceConfig::default()
        };
        let mut vi = VoiceInterface::new(config);

        vi.start_listening();
        assert!(vi.is_listening());
        assert_eq!(*vi.phase(), VoicePhase::Scanning);
    }

    #[test]
    fn test_toggle_listening() {
        let mut vi = VoiceInterface::new(VoiceConfig::default());

        let state = vi.toggle_listening();
        assert!(state);
        assert!(vi.is_listening());

        let state = vi.toggle_listening();
        assert!(!state);
        assert!(!vi.is_listening());
    }

    #[test]
    fn test_idempotent_start_stop() {
        let mut vi = VoiceInterface::new(VoiceConfig::default());

        // Double start should not duplicate events.
        vi.start_listening();
        vi.start_listening();
        assert!(vi.is_listening());

        // Double stop should not duplicate events.
        vi.stop_listening();
        vi.stop_listening();
        assert!(!vi.is_listening());
    }

    #[test]
    fn test_drain_events() {
        let mut vi = VoiceInterface::new(VoiceConfig::default());
        vi.start_listening();
        vi.stop_listening();

        let events = vi.drain_events();
        assert!(!events.is_empty());

        // Events cleared after drain.
        let events2 = vi.drain_events();
        assert!(events2.is_empty());
    }

    #[test]
    fn test_events_contain_phase_changes() {
        let mut vi = VoiceInterface::new(VoiceConfig::default());
        vi.start_listening();
        vi.stop_listening();

        let events = vi.drain_events();
        let phase_changes: Vec<&VoiceEvent> = events
            .iter()
            .filter(|e| e.event_type == "phase_change")
            .collect();
        assert!(phase_changes.len() >= 2); // idle->listening, listening->idle
    }

    #[test]
    fn test_set_auto_respond() {
        let mut vi = VoiceInterface::new(VoiceConfig::default());
        assert!(!vi.config().auto_respond);

        vi.set_auto_respond(true);
        assert!(vi.config().auto_respond);
        assert!(vi.get_status().auto_respond);

        let events = vi.drain_events();
        let ar_events: Vec<&VoiceEvent> = events
            .iter()
            .filter(|e| e.event_type == "auto_respond_changed")
            .collect();
        assert_eq!(ar_events.len(), 1);
        assert_eq!(ar_events[0].text.as_deref(), Some("enabled"));
    }

    #[test]
    fn test_voice_phase_display() {
        assert_eq!(format!("{}", VoicePhase::Idle), "idle");
        assert_eq!(format!("{}", VoicePhase::Scanning), "scanning");
        assert_eq!(format!("{}", VoicePhase::Listening), "listening");
        assert_eq!(format!("{}", VoicePhase::Recording), "recording");
        assert_eq!(format!("{}", VoicePhase::Processing), "processing");
        assert_eq!(format!("{}", VoicePhase::Speaking), "speaking");
    }
}
